name: fabiodominguez
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

    
  font_awesome_flutter: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  url_launcher: ^6.2.5
  flutter_launcher_icons: ^0.14.3
flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/images/ic_launcher.webp"
    web:
      generate: true
      image_path: "assets/images/ic_launcher.webp"
flutter:
  uses-material-design: true
  assets:
    - assets/profile.png